name: AKS-Infra-Deploy-Pipeline

trigger: none
  # branches:
  #   include:
  #     - main

parameters:
- name: environment
  type: string
  default: dev
  values:
    - dev
    - prod
    - qa

resources:
  pipelines:
  - pipeline: terraformPlan
    source: infra-plan-pipeline
    # in source, name of your plan pipeline, just skip the .yaml
    trigger:
      branches:
        include:
        - main


pool: dev-aks-akkc-agent


variables:
  # variable group is used to fetch backend secrets
  - group: tf_backend_vg
  # VG is used to pass the sub id to the .tfvars file. VG= variables group
  - group: subscription_vg

  # this condition is used to change the value of sub_id as per the parameter(like dev,qa,prod). 
  - ${{ if eq(parameters.environment, 'dev') }}:
      - name: sub_id
        value: $(dev_sub_id)

  - ${{ if eq(parameters.environment, 'qa') }}:
      - name: sub_id
        value: $(qa_sub_id)

  - ${{ if eq(parameters.environment, 'prod') }}:
      - name: sub_id
        value: $(prod_sub_id)

  # terraform statefile variables as per env, it will change as per parameter value.
  - name: statefile
    value: "axion-${{ parameters.environment }}.infra.tfstate"

  # we can not pass the service-connection value via VG
  - name: service-connection
    value: "axion-aks-app"

  # workig directory as per env
  - name: workdir
    value: '$(System.DefaultWorkingDirectory)/environment/${{ parameters.environment }}'


stages:
- stage: terraform_apply
  # dependsOn: terraform_plan
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  displayName: "Terraform Apply"
  jobs:
  - template: templates/jobs/terraform_apply_buildid.yaml
    parameters:
      environment: ${{ parameters.environment }}
      deploymentName: "terraform_apply"
      displayName: "Provisoning Infrastucture"
      workingDirectory: '$(workdir)'
      serviceConnection: '$(service-connection)'
      backendResourceGroup: '$(resource-group)'
      backendStorageAccount: '$(storage-account)'
      backendContainer: '$(blob-container)'
      backendStateFile: '$(statefile)'
      planPipelineId: '$(resources.pipeline.terraformPlan.runID)'


